name: Sync with template

on:
  push:
    branches:
      - main

permissions:
    contents: write
    pull-requests: write 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: "CloudAstro/terraform-azurerm-module-template"
          upstream_branch: "main"